.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .low, "ax"

/* Generated by spimdisasm 1.13.0 */

# Handwritten function
glabel osWritebackDCache
/* D6A0 8000E6A0 18A00011 */  blez       $a1, .L8000E6E8
/* D6A4 8000E6A4 00000000 */   nop
/* D6A8 8000E6A8 240B2000 */  addiu      $t3, $zero, 0x2000
/* D6AC 8000E6AC 00AB082B */  sltu       $at, $a1, $t3
/* D6B0 8000E6B0 1020000F */  beqz       $at, .L8000E6F0
/* D6B4 8000E6B4 00000000 */   nop
/* D6B8 8000E6B8 0080402D */  daddu      $t0, $a0, $zero
/* D6BC 8000E6BC 00854821 */  addu       $t1, $a0, $a1
/* D6C0 8000E6C0 0109082B */  sltu       $at, $t0, $t1
/* D6C4 8000E6C4 10200008 */  beqz       $at, .L8000E6E8
/* D6C8 8000E6C8 00000000 */   nop
/* D6CC 8000E6CC 2529FFF0 */  addiu      $t1, $t1, -0x10
/* D6D0 8000E6D0 310A000F */  andi       $t2, $t0, 0xF
/* D6D4 8000E6D4 010A4023 */  subu       $t0, $t0, $t2
.L8000E6D8:
/* D6D8 8000E6D8 BD190000 */  cache      0x19, 0x0($t0) # handwritten instruction
/* D6DC 8000E6DC 0109082B */  sltu       $at, $t0, $t1
/* D6E0 8000E6E0 1420FFFD */  bnez       $at, .L8000E6D8
/* D6E4 8000E6E4 25080010 */   addiu     $t0, $t0, 0x10
.L8000E6E8:
/* D6E8 8000E6E8 03E00008 */  jr         $ra
/* D6EC 8000E6EC 00000000 */   nop
.L8000E6F0:
/* D6F0 8000E6F0 3C088000 */  lui        $t0, 0x8000
/* D6F4 8000E6F4 010B4821 */  addu       $t1, $t0, $t3
/* D6F8 8000E6F8 2529FFF0 */  addiu      $t1, $t1, -0x10
.L8000E6FC:
/* D6FC 8000E6FC BD010000 */  cache      0x01, 0x0($t0) # handwritten instruction
/* D700 8000E700 0109082B */  sltu       $at, $t0, $t1
/* D704 8000E704 1420FFFD */  bnez       $at, .L8000E6FC
/* D708 8000E708 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
/* D70C 8000E70C 03E00008 */  jr         $ra
/* D710 8000E710 00000000 */   nop
